recettes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app.url', 'app'), namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.
class Recette(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=100, help_text="Concis. Majuscule seulement au début.")
    description = models.CharField(max_length=150, help_text="Description rapide et alléchante!")
    instructions = models.TextField()
    active = models.BooleanField(default=False)

    def veggie(self):
        for d in Dosage.objects.filter(recette_id=self.id):
            for i in Ingredient.objects.filter(id=d.ingredient_id):
                if (i.categorie == "viande") or (i.categorie == "poisson"):
                    return False
        return True
    veggie.boolean = True
    veggie.short_description = "Végé ?"



    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    recettes = models.ManyToManyField(Recette, related_name='recettes', blank=True, through='Dosage')

    class Categorie(models.TextChoices):
        legumes = 'legume', '🥕 Légume'
        fruit = 'fruit', '🍒 Fruit'
        feculent = 'feculent', '🌾 Féculent'
        epice = 'epice', '🌶 Épice'
        viande = 'viande', '🍗 Viande'
        poisson = 'poisson', '🐟 Poisson'
        laitage = 'laitage', '🥛 Laitage'
        sauce = 'sauce', '🥣 Sauce'
        autre = 'autre', '⭐️ Autre'
        inconnu = 'inconnu', '❌ Inconnu'

    categorie = models.CharField(max_length=25, choices=Categorie.choices, default=Categorie.inconnu)

    def __str__(self):
        return self.name

class Dosage(models.Model):
    recette = models.ForeignKey(Recette, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantite = models.IntegerField()

    class Unites(models.TextChoices):
        g = 'g', 'grammes'
        mL = 'mL', 'millilitres'
        cas = 'cas', 'cuillère à soupe'
        cac = 'cac', 'cuillère à cafe'
        p = 'pincee', 'pincée'
        t = 't', 'tranches'
        u = '.', 'unite'

    unite = models.CharField(max_length=20, choices=Unites.choices, default=Unites.g)

app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Recette

# Create your views here.
def index(request):
    context = { "foo": "Fbedjsfnjkqfs" }
    return render(request, 'app/index.html', context)

def listing(request):
    context = {}
    context["recettes"] = Recette.objects.all()
    return render(request, 'app/listing.html', context)

def detail(request, recette_id):
    recette = get_object_or_404(Recette, pk=recette_id)
    return render(request, 'app/details.html', {'recette': recette})

def search(request):
    return HttpResponse("ET ok")

app/templates/app/base.html
<html>
  <head>
    <title>Recettes hebdo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'app/css/styles.css' %}"
    />
    <script src="{% static 'app/js/jquery.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.js' %}"></script>
  </head>

  <body>
    <!-- Navbar -->
    {% include "../app/navbar.html" %}

    <!-- Body -->
    <div class="col align-baseline" id="overriding-bootstrap">
      {% block content %}{% endblock %}
    </div>

    <!-- Footer -->
    {% include "../app/footer.html" %}
  </body>
</html>

app/templates/app/details.html
{% extends 'app/base.html' %}
{% load markdown_deux_tags %}

{% block content %}
  <h1> {{ recette.name }} </h1>

  <p> {{ recette.description }} </p>

  <h2> Instructions </h2>
  <p>
    {{ recette.instructions | markdown }}
  </p>
{% endblock %}

app/templates/app/footer.html
<footer class="page-footer font-small blue pt-4">

<!-- Copyright -->
<div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://blog.ewen.quimerch.com/"> Ewen Quimerc'h</a>
    <br>
    <a href="https://recettes.quimerch.com/admin">Admin</a>
</div>


</footer>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
  <p>Bienvenue sur le site de recommandations de recettes</p>
  <p>La page est encore en cours de construction !</p>
{% endblock %}

app/templates/app/listing.html
{% extends 'app/base.html' %}

{% block content %}
  <h2>Toutes les recettes</h2>

  {% load static %}
  <div class="container">
    <div class="row">
    {% for recette in recettes %}
      <div class="col">

        <div class="m-1">
          
        <!-- Card with recipe sum-up -->
        <div class="card" style="width: 18rem;">

          <!-- Load image or display thumbnail -->
          {% with 'app/img/recettes/'|add:recette.name|add:'.webp'|lower as image_static %}
          <img class="card-img-top" src="{% static image_static %}" alt=" ">
          {% endwith %}


          <div class="card-body">
            <h5 class="card-title">{{ recette.name }}</h5>
            <p class="card-text">{{ recette.short }}</p>
            <a href="{% url 'app:recettes' %}{{recette.id}}" class="btn btn-primary stretched-link">Cuisiner !</a>
          </div>
        </div>

        
        </div>

      </div>
    {% endfor %}
    </div>
  </div>

{% endblock %}

app/templates/app/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="{% url 'app:index' %}">Recettes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:index' %}">Accueil <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
        <a class="nav-link" href="{% url 'app:recettes' %}">Toutes les recettes</a>
        </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
</nav>